# Generated by Django 3.2.6 on 2024-05-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobdescriptionchunk_token_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescriptionchunk',
            name='token_count',
        ),
    ]
