# Generated by Django 3.2.6 on 2024-05-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_jobdescriptionchunk_token_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescriptionchunk',
            name='token_count',
            field=models.IntegerField(null=True),
        ),
    ]
