# Generated by Django 3.2.6 on 2024-05-29 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jobdescriptionchunk_token_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('citation', models.CharField(max_length=255)),
                ('book', models.CharField(max_length=255)),
                ('chapter', models.IntegerField(default=0)),
                ('verse', models.IntegerField(default=0)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
