# Generated by Django 3.2.6 on 2024-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bible'),
    ]

    operations = [
        migrations.AddField(
            model_name='bible',
            name='token_count',
            field=models.IntegerField(null=True),
        ),
    ]
